services:
  # devops exercises service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bw-devops-exercise:latest
    container_name: bw-devops-exercise
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    ports:
      - 8081:8080
    networks:
      - app-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:8081"
    networks:
      - app-network

  # Docker Networks
networks:
  app-network:
    driver: bridge