apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-app
    namespace: {{ .Release.Namespace }}
spec:
    selector:
        app: {{ .Release.Name }}-app
        role: web
    ports:
      - name: http
        port: 80
        targetPort: 8080
