apiversion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
  namespace: {{ .Release.Namespace }}
  spec: 
    replicas: {{ .Values.web.replicas}}
    selector:
      matchLabels:
        app: {{ .Release.Name }}-web
    template:
        metadata:
            labels:
                app: {{ .Release.Name }}-web
        spec:
            containers:
                - name: {{ .Release.Name }}-web
                  image: {{ .Values.web.image }}
                  ports:
                    - containerPort: 8080