apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
    tls:
    - hosts:
      - myapp.com
      secretName: myapp-tls
spec:
    rules:
    - host: myapp.com
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ $.Release.Name }}-app
            servicePort: 80