name: Run Tests

on:
  push:
    branches:
    - master
  pull_request:
    types: [opened, synchronize]
jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-22.04

    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install pipenv
      run: pip install pipenv
    - name: Install dependencies
      run: |
        pipenv install --deploy
        pipenv install --dev --deploy
    - name: Run unit tests
      run: pipenv run pytest
  
